groups:
- name: instance.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 20s
    labels:
      severity: page
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has been down for
        more than 5 minutes.'
      summary: Instance {{$labels.instance}} down